script: "rspec spec"
language: "ruby"
rvm:
  - 3.0.4
  - 3.1.2
  - jruby
gemfile:
  - Gemfile
  - Gemfile.rails-3.2.x
  - Gemfile.rails-4.0.x
notifications:
  disable: true

matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: jruby
      gemfile: Gemfile
